/* tslint:disable */
/* eslint-disable */
/**
 * ChatRoomsWeb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ChatData } from './chat-data';
import { Message } from './message';
 /**
 * 
 *
 * @export
 * @interface Chat
 */
export interface Chat {

    /**
     * @type {ChatData}
     * @memberof Chat
     */
    chatData?: ChatData;

    /**
     * @type {Array<Message>}
     * @memberof Chat
     */
    messages?: Array<Message> | null;
}
