/* tslint:disable */
/* eslint-disable */
/**
 * ChatRoomsWeb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ChatData
 */
export interface ChatData {

    /**
     * @type {string}
     * @memberof ChatData
     */
    id?: string | null;

    /**
     * @type {string}
     * @memberof ChatData
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof ChatData
     */
    description?: string | null;

    /**
     * @type {string}
     * @memberof ChatData
     */
    ownerUsername?: string | null;

    /**
     * @type {Date}
     * @memberof ChatData
     */
    dateTimeCreated?: Date;

    /**
     * @type {Array<string>}
     * @memberof ChatData
     */
    activeChatters?: Array<string> | null;

    /**
     * @type {number}
     * @memberof ChatData
     */
    totalMessages?: number;
}
