/* tslint:disable */
/* eslint-disable */
/**
 * ChatRoomsWeb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum RegionsEnum {
    WORLD = 'WORLD',
    EMEA = 'EMEA',
    NA = 'NA',
    LATAM = 'LATAM',
    APAC = 'APAC'
}

