/* tslint:disable */
/* eslint-disable */
/**
 * ChatRoomsWeb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Message } from './message';
 /**
 * 
 *
 * @export
 * @interface UserInfo
 */
export interface UserInfo {

    /**
     * @type {Array<Message>}
     * @memberof UserInfo
     */
    messagesSent?: Array<Message> | null;

    /**
     * @type {Array<string>}
     * @memberof UserInfo
     */
    favouritedChatsIds?: Array<string> | null;

    /**
     * @type {Array<string>}
     * @memberof UserInfo
     */
    createdChatsIds?: Array<string> | null;
}
